language: php

php:
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then phpunit; fi
